### ISSUE TITLE
Avoid breaking when DBnomics API upgrades

### ISSUE THREAD

**Issue by cbenz** [dbnomics-stata/dbnomics#1]
Hi @dreameater89 !

I am a developer of the DBnomics team. We already discussed [here](https://forum.db.nomics.world/t/about-the-stata-plugin/126/14).

I just wanted to recommend that you put the version number of the web API of DBnomics in your `apipath` variable (at [this line](https://github.com/dreameater89/dbnomics/blob/125b744d6702e3cdbfa9d8eccf87ad8abc35230a/dbnomics.ado#L42) if I'm not mistaken). Otherwise, when we'll release a major version of DBnomics API, suddently the users of your Stata library will face errors, because URL paths, query-string parameters or JSON responses will have changed.

It turns out that we are preparing a v22 in pre-production, available at https://api.dev.nomics.world/v22/ (documentation available [here](https://api.dev.nomics.world/v22/apidocs)). You could also start a new branch to adapt your code to the new version. We're going to start updating the [Python module for DBnomics](https://git.nomics.world/dbnomics/dbnomics-python-client) in a couple of days. After that we'll be able to publish a migration guide.

**Comment by dbnomics-stata** [comment]
Hello @cbenz !

Many thanks for this! This is now fixed in version 1.2.0 of the command, which now elicits the API version and should be robust to API version changes. And by the way, the command is now (finally) compliant with API v22.
