### ISSUE TITLE
Issue with IMF/IFS

### ISSUE THREAD

**Issue by ademeo37** [dbnomics-stata/dbnomics#3]
I have encountered the following problem when trying to import a variable (namely HPUPQ_PA, but the problem applies to every variable) from the IMF/IFS database with Stata 15. The command:

dbnomics import, provider(IMF) dataset(IFS) indicator(HPUPQ_PA) clear

yields no results (i.e. “no series found” error).

**Comment by dbnomics-stata** [comment]
Hi, note that the options in dbnomics are case sensitive, to reflect the data structure of each specific provider. In this particular case, the dimension "indicator" has to be in all caps, so this should work:

dbnomics import, pr(IMF) d(IFS) INDICATOR(HPUPQ_PA) clear limit(1)
